import type {
  ClipboardGroupRecord,
  ClipboardItem,
  ClipboardItemPage,
} from "@/types/clipboard";
import type { Settings } from "@/types/settings";

export const DEFAULT_MOCK_SETTINGS: Settings = {
  appearance: {
    language: "zh-CN",
    theme: "light",
  },
  clipboard: {
    capture: {
      files: true,
      html: true,
      image: true,
      maxImageMb: 100,
      maxTextMb: 4,
      order: ["files", "image", "html", "rtf", "text"],
      rtf: true,
      text: true,
    },
    content: {
      autoFavorite: false,
      autoPaste: "doubleClickPaste",
      copyPlain: false,
      copyThenHideWindow: false,
      deleteConfirm: true,
      deleteFavoriteConfirm: true,
      deleteFavoriteItems: false,
      deleteFavoriteItemsOnlyInFavoriteGroup: true,
      deletePinnedConfirm: true,
      deletePinnedItems: false,
      itemActionOrder: [
        "paste",
        "pastePlain",
        "pastePath",
        "copy",
        "copyPlain",
        "openLink",
        "sendEmail",
        "reveal",
        "note",
        "star",
        "pinItem",
        "delete",
      ],
      itemActions: ["copy", "star", "pinItem", "delete"],
      middleClick: "disabled",
      pasteFilesAsPath: false,
      pastePlain: false,
      showOriginalPreview: true,
      sort: "updatedAtDesc",
      updateOnReuse: false,
    },
    display: {
      fileMaxCount: 3,
      imageMaxHeight: 64,
      textMaxLines: 4,
    },
    feedback: {
      copySound: false,
    },
    filters: {
      excludedAppIds: [],
    },
    history: {
      cleanupIntervalHours: 24,
      maxCount: 1000,
      retention: {
        unit: "forever",
        value: 0,
      },
    },
    preview: {
      hoverDelayMs: "ms500",
      hoverEnabled: false,
      spaceEnabled: true,
    },
    search: {
      clearOnHide: true,
      defaultFocus: false,
    },
    sensitive: {
      collectSecrets: true,
      redactSecrets: true,
    },
    window: {
      idleDestroySeconds: 60,
      lightweightMode: true,
      position: "center",
      scrollToTopOnOpen: true,
      selectCategoryOnOpen: "preserve",
      selectGroupOnOpen: "preserve",
      selectRangeOnOpen: "preserve",
    },
  },
  general: {
    autoStart: false,
    dockIcon: false,
    runAsAdmin: false,
    trayIcon: true,
  },
  onboarding: {
    completed: true,
    lastStep: 0,
    legacyImport: {
      checked: false,
      imported: false,
      importedAt: null,
      importTypes: [],
    },
  },
  shortcuts: {
    openClipboard: "Alt+C",
    openPreference: "Alt+X",
    winV: false,
  },
  update: {
    autoCheck: true,
    frequency: "daily",
    includeBeta: false,
    includeNightly: false,
    lastCheckedAt: null,
    skippedVersion: null,
  },
};

export const MOCK_GROUPS: ClipboardGroupRecord[] = [
  {
    createdAt: new Date().toISOString(),
    icon: "i-lets-icons:widget",
    id: "group-1",
    isHidden: false,
    name: "未命名",
    sortOrder: 0,
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_ITEMS: ClipboardItem[] = [
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
    ],
    content: "Paste 风格主界面概念图",
    contentHash: "hash-1",
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: null,
    id: "mock-1",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "text",
    note: null,
    platform: "macos",
    searchText: null,
    size: 24,
    sourceAppId: "company.thebrowser.Browser",
    sourceAppName: "Arc",
    subKind: null,
    summary: "Paste 风格主界面概念图",
    updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    useCount: 1,
    width: null,
  },
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
    ],
    content: "空格键 Quick Look 预览概念图",
    contentHash: "hash-2",
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: null,
    id: "mock-2",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "text",
    note: null,
    platform: "macos",
    searchText: null,
    size: 32,
    sourceAppId: "company.thebrowser.Browser",
    sourceAppName: "Arc",
    subKind: null,
    summary: "空格键 Quick Look 预览概念图",
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    useCount: 1,
    width: null,
  },
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
    ],
    content: "requestbagger",
    contentHash: "hash-3",
    createdAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: null,
    id: "mock-3",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "text",
    note: null,
    platform: "macos",
    searchText: null,
    size: 13,
    sourceAppId: "com.openai.chat",
    sourceAppName: "ChatGPT",
    subKind: null,
    summary: "requestbagger",
    updatedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    useCount: 1,
    width: null,
  },
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
    ],
    content:
      'tradeV2 接收到请求头信息\nheaders={"appsource": ["6"],"x-b3-parentspanid": ["5a0d3d240b342a5e"],"uphost": ["payment-core-7fb546db98-twmvp"],"content-length": ["1989"],"countrycode": ["NG"],"x-b3-sampled": ["1"]}',
    contentHash: "hash-4",
    createdAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: null,
    id: "mock-4",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "text",
    note: null,
    platform: "macos",
    searchText: null,
    size: 1379,
    sourceAppId: "com.google.Chrome",
    sourceAppName: "Google Chrome",
    subKind: null,
    summary:
      'tradeV2 接收到请求头信息\nheaders={"appsource": ["6"],"x-b3-parentspanid": ["5a0d3d240b342a5e"],"uphost": ["payment-core-7fb546db98-twmvp"],"content-length": ["1989"],"countrycode": ["NG"],"x-b3-sampled": ["1"]}',
    updatedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    useCount: 1,
    width: null,
  },
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
      "openLink",
    ],
    content: "https://palmpay.yuque.com/ffgots/wb4n",
    contentHash: "hash-5",
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: null,
    id: "mock-5",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "text",
    note: null,
    platform: "macos",
    searchText: null,
    size: 37,
    sourceAppId: "com.google.Chrome",
    sourceAppName: "Google Chrome",
    subKind: "url",
    summary: "palmpay.yuque.com/ffgots/wb4n",
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    useCount: 1,
    width: null,
  },
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
    ],
    content: "preview.png",
    contentHash: "hash-6",
    createdAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: 1138,
    id: "mock-6",
    imageThumbnailPath: "/logo.png",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "image",
    note: null,
    platform: "macos",
    searchText: null,
    size: 256800,
    sourceAppId: "com.google.Chrome",
    sourceAppName: "Google Chrome",
    subKind: null,
    summary: "image_preview",
    updatedAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    useCount: 1,
    width: 2568,
  },
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
    ],
    content:
      'TradeCheckController_tradeV2RequestHeaders and msg: "true-client-ip()"',
    contentHash: "hash-7",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: null,
    id: "mock-7",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "text",
    note: null,
    platform: "macos",
    searchText: null,
    size: 71,
    sourceAppId: "com.google.Chrome",
    sourceAppName: "Google Chrome",
    subKind: null,
    summary:
      'TradeCheckController_tradeV2RequestHeaders and msg: "true-client-ip()"',
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    useCount: 1,
    width: null,
  },
  {
    availableActions: [
      "copy",
      "paste",
      "delete",
      "toggleFavorite",
      "togglePinned",
    ],
    content: "true-client-ip",
    contentHash: "hash-8",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    fileTypes: null,
    groupId: null,
    height: null,
    id: "mock-8",
    isFavorite: false,
    isPinned: false,
    isSensitive: false,
    kind: "text",
    note: null,
    platform: "macos",
    searchText: null,
    size: 14,
    sourceAppId: "com.google.Chrome",
    sourceAppName: "Google Chrome",
    subKind: null,
    summary: "true-client-ip",
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    useCount: 1,
    width: null,
  },
];

export const MOCK_PAGE: ClipboardItemPage = {
  hasMore: false,
  list: MOCK_ITEMS,
  total: MOCK_ITEMS.length,
};
