[package]
name = "ecopaste-sync-protocol"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
minicbor = { version = "2", features = ["derive", "std"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["io-util", "macros", "rt"] }
